name: PR Docker Build Test

on:
  pull_request:
    branches:
      - main
    paths: ['sc-server/**', '.github/workflows/deployment.yml']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            server:
              - 'sc-server/**'
              - '.github/workflows/deployment.yml'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        if: steps.filter.outputs.server == 'true'
        uses: docker/build-push-action@v6
        with:
          context: '{{defaultContext}}:sc-server'
          push: false
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sc-server:test

      - name: Run tests in Docker
        if: steps.filter.outputs.server == 'true'
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/sc-server:test /bin/sh -c "curl localhost:3000"
